language: python
sudo: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

before_install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

install:
  - python -m pip install

script:
  - pytest --cov=geocoder tests

after_success:
  - codecov

notifications:
  email:
    - carriere.denis@gmail.com
